apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alien2003/argocd-test.git
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
        - values.yaml
        - ../environments/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-test
  syncPolicy:
    automated:
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
